version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: ${MYSQL_PORT}
            user: root
            password: ${MYSQL_ROOT_PASSWORD}
            database: jdbc:mysql://root:${MYSQL_ROOT_PASSWORD}@mysql-db:${MYSQL_PORT}/seikyoIntegration?verifyServerCertificate=false&useSSL=false

      # connectionTimeout: 60000

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: jdbc:mysql://root:${MYSQL_ROOT_PASSWORD}@mysql-db:${MYSQL_PORT}/seikyoIntegration?verifyServerCertificate=false&useSSL=false
    depends_on:
      - prisma

volumes:
  mysql:
